### ISSUE TITLE
Simultaneous reception on Comm 1 & 2

### ISSUE THREAD

**Issue by joecampbell42** [TheFrett/msfs_g36_project#63]
The C152 community modders were able to figure this one out. When on the networks (VATSIM/Pilotedge) it is often useful to be able to receive on two frequencies while transmitting on one. (Picking up ATIS while being controlled by radar/monitoring guard frequencies are two examples) The user "DRF30q" on the forums was able to figure this out for the 152 and make it functional with the vPilot client. I don't know much about coding and stuff but I've reached out to him to see if he has any guidance. I will update as I receive the information. Thank you!

**Comment by tigert** [comment]
PilotEdge / Vatsim / IVAO pilot apps very likely depend on "COM RECEIVE BOTH" simconnect variable. 

The reason this does not work on the G1000 planes right now, is because there is no "BOTH" button on the G1000 audio panel - instead it has separate "audio" buttons for both COM1 and COM2 that you can toggle on or off independently (with the caveat that the one where your MIC selector points to is always on, for obvious reasons).

This is something that could perhaps be added to the Working Title G1000 mod, so that it sets the BOTH flag whenever the separate COM1 and COM2 audio outputs are simultaneously enabled. But the mod currently does not touch the audio panel code XML logic at all.

This will actually work with a workaround: if you somehow enable "COM RECEIVE BOTH" variable via simconnect or FSUIPC. I do this with my home cockpit setup, that uses mobiflight, but I think you can also map keys and joystick buttons to Simconnect events using FSUIPC.

**Comment by tigert** [comment]
This now works with the latest sim update btw.

So this can be closed.
